# admin
admin_mixin_uuid: 7ed9292d-7c95-4333-aa48-a8c640064186

# redis
redis:
  namespace: mixcoin_plus

# action cable
action_cable:
  namespace: mixcoin_plus_cable

# sidekiq
sidekiq:
  namespace: mixcoin_plus_sidekiq

# MixSwap
mix_swap:
  enable: true

# 4swap
foxswap:
  mtg_members:
    - a753e0eb-3010-4c4a-a7b2-a7bda4063f62 
    - 099627f8-4031-42e3-a846-006ee598c56e 
    - aefbfd62-727d-4424-89db-ae41f75d2e04 
    - d68ca71f-0e2c-458a-bb9c-1d6c2eed2497 
    - e4bc0740-f8fe-418c-ae1b-32d9926f5863
  mtg_threshold: 3
  mtg_public_Key: dt351xp3KjNlVCMqBYUeUSF45upCEiReSZAqcjcP/Lc=
  enable: true
